### ISSUE TITLE
[Я] Дорожная карта

### ISSUE THREAD

**Issue by avoika** [technolider/RSP-demo#30]

**Comment by artemetr** [comment]
В дорожной карте лишние пункты про декомпозицию задач разработчиков, это этап разработки а не проекта

**Comment by avoika** [comment]
оки доки
дорожная карта (нормальная)
1. анализ ситуации
2. поиск проблемы
3. формулирвока проектного замысла
5. разработка
 ---мы сейчас---
6. внедрение в отдел эйчар
7. доработка
8. поиск инвесторов
9. разработка основных сервисов
10. выход в прод

**Comment by artemetr** [comment]
1. Разработка MVP
2. Внедрение в отдел эйчар
3. Доработка
4. Поиск инвесторов
5. Разработка основных сервисов
6. Выход в прод
