### ISSUE TITLE
[Я] Видео

### ISSUE THREAD

**Issue by artemetr** [technolider/RSP-demo#6]

**Comment by Borzes** [comment]
*По времени как раз на две минуты

ВИДЕО

Лаборатория IT занималась разработкой прототипа RSP системы.

По данным IDC в 2020 году 42% российских компаний работают на SAP ERP - системе для автоматизации бизнес-процессов.
Сегодня SAP ERP уходит с российского рынка и прекращает поддерживать и обновлять ПО для компаний. Однако альтернативных программ на рынке нет, поэтому перейти на другую систему невозможно.

Проектный замысел - создать новое программное обеспечение на основе абсолютно нового подхода к организации бизнес-процессов предприятия - RSP. Основные преимущества RSP перед ERP: диверсификация услуг и паралелльность процессов.
На смене айти лаборатория реализовала прототип RSP системы в рамках работы HR отдела, где были автомаизированы поиск, подбор и прием кандидатов.

RSP система состоит из сервисов - моделей отделов компании. Сервисы имеют свои услуги и базы данных. Также есть интерфейс взаимодействия пользвователя и каталог сервисов.

Все начинается с поиска: руководитель отдела создает заявку на нового работника. Во время работы над этой заявкой система будет менять ее статусы, что позволит отслеживать готовность. После создания заявки система автоматически запрашивает портрет работника, ищет похожие в кадровом резерве, связывается с найденными людьми. Или создает новую вакансию, которая размещается на поисковых ресурсах. Все откликнувшиеся попадают на собеседование - этап прямого взаимодейтсвия HR-а с кандидатом. Поэтому здесь HR меняет статусы заявки вручную. 
После идет подбор: система высылает отобраным кандидатам офферы с предложением о работе. Этап приема начинается с подписания трудового договора. Здесь работника обеспечивают необходимыми ресурсами: рабочим местом, техникой, питанием и тд. В этот момент зона ответсвенности HR сервиса заканчивается и задачи обеспечения переходят в другие сервисы, что демонстрирует главный плюс RSP - диверсификацию.

По итогам работы IT-лаборатория создала полностью работающий прототип RSP системы в рамках сервиса HR.

В будущем планируется внедрение прототипа в HR отделы компаний, доработка ПО, поиск инвесторов и выход на рынок.

@artemetr , посмотри, что как

**Comment by artemetr** [comment]
**2:38**

Лаборатория IT занималась разработкой прототипа RSP системы.

По данным исследовательской компании IDC на 2020 год 42% российских компаний работают на базе SAP ERP - системы для автоматизации бизнес-процессов.
SAP ERP не отличается гибкостью, быстрым внесением изменений в процессы и user-friendly интерфейсом. Так же компания SAP уходит с российского рынка и прекращает поддержку своих продуктов. 
Полноценной замены SAP ERP, решающей все классы задач, нет.

Решить эту проблему могло бы создание нового программного обеспечения на основе абсолютно иного подхода к организации бизнес-процессов предприятия – RSP.

Преимуществами RSP перед ERP-подходом является диверсификация, параллельность и прозрачность процессов.

На смене, лаборатория IT реализовала прототип RSP-системы на примере работы HR-отдела, где для автоматизации были рассмотрены процессы поиска, подбора и приёма кандидатов.

Разработанная архитектура системы позволяет разделить исходный монолит ERP на обособленные отделы.
Таким образом иерархическая структура управления преобразуется в матричную, а размытые ранее зоны ответственности, без инструментов влияния, преобразуются в сервисы, как отражения отделов в виртуальной среде, с единой точкой ответственности, ограниченной услугами, которые предоставляет сервис.

При такой модели ясна стоимость и нагрузка каждого из отделов. Эта прозрачность позволит принимать обоснованные управленческие решения.

Во время работы в лаборатории мы спроектировали и разработали базовый механизм обмена сообщениями между сервисами. Он построен на использовании очередей. Если на любом из этапов нам нужна дополнительная информация, она сможет запроситься у заказчика услуги через сквозной проброс интерфейса. Такой диалоговый способ общения между сервисами и пользователем позволяет избежать передачи избыточной информации, при этом из любого места системы, информация может быть получена вновь.

Реализован гибкий и адаптивный интерфейс приложения. Он принимает информацию об ожидаемых данных и рендерит необходимую пользовательскую форму. Такой подход обеспечивает простоту изменения структуры и валидации данных. Если для услуги станет необходим другой набор данных, то интерфейс изменится автоматически.

Как итог в ходе работы в IT-лаборатории мы создали прототип RSP системы в рамках сервиса HR, включающий в себя механизм обмена сообщениями, архитектуру и графический интерфейс пользователя. Для реализации функций HR-департамента на базе нашего прототипа мы уже проанализировали устройство внутренних HR-процессов, составили алгоритмы их работы и сформировали техническое задание на разработку.

В будущем планируется реализация HR-услуг в рамках прототипа и переход к MVP. Тестирование MVP позволит выявить принципиальные недостатки системы и исправить их для последующего поиска финансирования и выхода на рынок.

**Comment by avoika** [comment]
текст от тёмы

Лаборатория IT занималась разработкой прототипа RSP системы.

По данным исследовательской компании IDC на 2020 год 42% российских компаний работают на базе SAP ERP - системы для автоматизации бизнес-процессов.
SAP ERP не отличается гибкостью, быстрым внесением изменений и user-friendly интерфейсом. Так же компания SAP уходит с российского рынка и прекращает поддержку своих продуктов.
Полноценной замены SAP ERP, решающей все классы задач, нет.

Решением может стать создание нового программного обеспечения на основе абсолютно иного подхода к организации бизнес-процессов предприятия – RSP.

Преимуществами RSP перед ERP-подходом являются диверсификация, параллельность и прозрачность процессов.

На смене, лаборатория IT реализовала прототип RSP-системы на примере работы HR-отдела, где для автоматизации мы рассмотрели процессы поиска и приёма кандидатов.

Созданная архитектура системы делит монолит ERP на обособленные отделы.
Иерархическая структура управления преобразуется в матричную, а размытые зоны ответственности - в сервисы. Они, являясь виртуальными моделями отделов, имеют единую точку ответственности и определенные услуги.

При такой модели ясны стоимость и нагрузка каждого отдела. Эта прозрачность гарантирует обоснованные управленческие решения.

Во время работы мы спроектировали и разработали базовый механизм обмена сообщениями между сервисами. Он построен на использовании очередей. Если нужна дополнительная информация, она запрашивается у заказчика услуги через сквозной проброс интерфейса. Такой диалоговый способ общения между сервисами и пользователем защищает от передачи избыточной информации. При этом из любого места системы информацию можно получить вновь.

Реализован гибкий и адаптивный интерфейс приложения. Он обрабатывает информацию об ожидаемых данных, создавая необходимую пользовательскую форму. Такой подход обеспечивает простоту изменения структуры и валидацию данных. При другом наборе данных интерфейс меняется автоматически.

По итогу мы создали прототип RSP системы в рамках сервиса HR, включающий в себя механизм обмена сообщениями, архитектуру и графический интерфейс пользователя.  Для реализации функций HR-департамента на базе нашего прототипа мы уже проанализировали устройство внутренних HR-процессов, составили алгоритмы их работы и сформировали техническое задание на разработку.

В будущем планируется реализация HR-услуг в рамках прототипа и переход к MVP. Тестирование MVP позволит выявить принципиальные недостатки системы и исправить их для последующего поиска финансирования и выхода на рынок.
